# scheduler:
#   system: "system:events"
#   pub: "scheduler:events"
#   state: "scheduler:state"
#   scene_load: "scheduler:scene_loaded"
#   scene_activate: "scheduler:scene_activated"

timezone: "Asia/Kolkata"

scales:
  cct:
    min: 3500
    max: 6500
  lux:
    min: 0
    max: 500

services:
  redis:
    redis_url: "redis://redis:6379/0"

  tcp:
    tcpserver:
      host: "luminaire-service"
      port: 5250
      keepalive_enabled: true
      keepalive_idle_s: 5
      keepalive_interval_s: 2
      keepalive_count: 3
      tcp_user_timeout_ms: 3000

    redis:
      pub: "devices:luminaires"

    fastAPI:
      host: "luminaire-service"
      port: 8000
      loop: "asyncio"
      log_level: "info"
      access_log: False

  state:
    redis:
      pub: "system:events"

    cors_origins:
      - "http://localhost"
      - "http://127.0.0.1"
      - "http://localhost:8080"
      - "http://127.0.0.1:8080"

    fastAPI:
      host: "state-api"
      port: 8001
      loop: "asyncio"
      log_level: "info"
      access_log: False

  scheduler:
    scenes_dir: "/app/scheduler_service/scenes"
    interval: 1 #seconds
    luminaire_service_url: "http://luminaire-service:8000/devices/luminaires/set"

    redis:
      pub: "scheduler:events"

  timer:
    state_service_url: "http://state-api:8001/system/power"    
    
    redis:
      pub: "timer:events"
  
  metrics:
    interval: 1
    redis:
      pub: "metrics:events"

event_gateway:
  service:
    name: event-gateway
    port: 8088
    log_level: info
    state_service_url: http://state-api:8001/state
  redis:
    url: redis://redis:6379/0
    reconnect_strategy_ms: 9000
  channels:
    scheduler: scheduler:events
    luminaires: devices:luminaires
    timer: timer:events
    metrics: metrics:events
  sse:
    heartbeat_interval_ms: 20000
    client_write_timeout_ms: 5000
    latency_interval_ms: 2000

ui:
  cct:
    min: 2000
    max: 7000
    default: 5000
    unit: "K"
    color: "#10b981"
  intensity:
    min: 0
    max: 700
    default: 250
    unit: "lux"
    color: "#f97316"
  polling_interval_ms: 2000
  latency_interval_ms: 2000
