version: "3.8"
services:
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis-data:/data
    environment:
      - TZ=Asia/Kolkata
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped


  api-service:
    build:
      context: ./$API_APP
      args:
        APP_NAME: $API_APP
        APP_PORT: $API_PORT
        MAIN_MODULE: api_service/main.py
        APP_USER: $APP_USER
    container_name: $API_APP
    environment:
      - TZ=Asia/Kolkata
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "$API_PORT:$API_PORT"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    healthcheck:
      test: [
        "CMD-SHELL",
         curl -f http://luminaire-service:5555/docs && 
         curl -f http://scheduler-service:6666/docs || exit 1"
        ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

  luminaire-service:
    build:
      context: ./$LUMINAIRE_APP
      args:
        APP_NAME: $LUMINAIRE_APP
        APP_PORT: $LUMINAIRE_PORT
        MAIN_MODULE: luminaire_service/main.py
        APP_USER: $APP_USER
      container_name: $LUMINAIRE_APP
    environment:
      - TZ=Asia/Kolkata
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "$LUMINAIRE_PORT:$LUMINAIRE_PORT"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://luminaire-service:8888/list || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

  scheduler-service:
    build:
      context: ./$SCHEDULER-APP
      args:
        APP_NAME: $SCHEDULER-APP
        APP_PORT: $SCHEDULER_PORT
        MAIN_MODULE: scheduler_service/main.py
        APP_USER: $APP_USER
    container_name: $SCHEDULER-APP
    environment:
      - TZ=Asia/Kolkata
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "$SCHEDULER_PORT:$SCHEDULER_PORT"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    healtcheck:
      test: ["CMD-SHELL", ""]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

  monitoring-service:
    build:
      context: ./$MONITORING_APP
      args:
        APP_NAME: $MONITORING_APP
        APP_PORT: $MONITORING_PORT
        MAIN_MODULE: monitoring_service/main.py
        APP_USER: $APP_USER
    container_name: $MONITORING_APP
    environment:
      - TZ=Asia/Kolkata
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "$MONITORING_PORT:$MONITORING_PORT"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    depends_on:
        redis:
          condition: service_healthy

  websocket-service:
    build:
      context: ./$WEBSOCKET_APP
      args:
        APP_NAME: $WEBSOCKET_APP
        APP_PORT: $WEBSOCKET_PORT
        MAIN_MODULE: websocket_service/main.py
        APP_USER: $APP_USER
    container_name: $WEBSOCKET_APP
    environment:
      - TZ=Asia/Kolkata
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "$WEBSOCKET_PORT:$WEBSOCKET_PORT"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    depends_on:
        redis:
          condition: service_healthy

  webapp:
    build:
      context: ./$WEBAPP
      args:
        APP_USER: $APP_USER
    container_name: $WEBAPP
    ports:
      - "$WEBAPP_PORT:80"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    depends_on:
      - websocket-service
  
  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      luminaire-service:
        condition: service_healthy
      scheduler-service:
        condition: service_healthy
      monitoring-service:
        condition: service_healthy
      websocket-service:
        condition: service_started

volumes:
   redis-data:
   prometheus-data: