{
 "title": "Luminaire Control Sys SRE Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Luminaire Stack Info Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=~\".+\", service_name!~\"grafana|alloy|loki|homeassistant|metrics-service|luminaire-service|timer-service\"} | level=\"info\""
    }
   ]
  },
  {
   "title": "Luminaire Stack Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=~\".+\", service_name!~\"grafana|alloy|loki|homeassistant\"} | level=\"error\""
    }
   ]
  },
  {
   "title": "Luminaire Service - ack / broadcast",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"luminaire-service\"} | json | event=~\"ack_published|broadcast_queued\""
    }
   ]
  },
  {
   "title": "Timer Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"timer-service\"}"
    }
   ]
  },
  {
   "title": "microservice event volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(service) (count_over_time({container=~\".+\"} | json | event!=\"\" [$__auto]))"
    }
   ]
  },
  {
   "title": "error rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(service) (rate({container=~\".+\"} | level=~\"error|critical|fatal|50\" [$__auto]))"
    }
   ]
  }
 ]
}